export const stationName = {
"Em" : "Emmaboda",
"Kac" : "Kalmar",
"Ck" : "Karlskrona",
"Nyb" : "Nybro",
"M" : "Malmö",
"Vö" : "Växjö",
"Hm" : "Hässleholm",
"Hvp" : "Hovmantorp",
"G" : "Göteborg",
"Av" : "Alvesta",
"Cst" : "Stockholm",
"Sdy" : "Smedby",
"Tre" : "Trekanten",
"Sdy" : "Smedby",
"Vfa" : "Vissefjärda",
"Hmö" : "Holmsjö",
"Örs" : "Örsjö",
"Båa" : "Bergåsa",
"Lo" : "Lessebo",
};
